insert into library values (1, 'learn java, learn scala, learn AWS','Technology library');
insert into library values (2, 'Mars Red Planet, Titan with water','Space Library');
insert into library values (3, '','Animal library');
insert into library values (4, '','Cloud Library');
insert into library values (5, 'Yellow Sun, Blue star, Red star','Star Library');
insert into library values (6, 'Life of tommy, Life of Brownie','Dogs Library');
insert into library values (7, 'xyz, abc, efg','A Library');
insert into library values (8, 'xyz, abc, efg','B Library');
insert into library values (9, 'xyz, abc, efg','D Library');
insert into library values (10, 'xyz, abc, efg','C Library');
insert into Customer values (1, 'ADMIN','$2a$12$Y9XN7KsST5m6IWrbxVrNhuPcslnmJsJqnXineJRMbYNQmjLz6WYiW','rkm1');
insert into Customer values (2, 'USER','$2a$12$RlBU1CJyhXF3WTLgUY33uOtVG15/S1ep0ROW7tK0u811kFLJwS/wC','rkm2');
insert into Customer values (3, 'USER','$2a$12$oHnfzIXGwOKMAjNHEJ4JNuei3g2JBGTJTBfHYf7/G2xwMF.OXJjrW','rkm3');